network:
  ethernets:
    ens18:
      dhcp4: false
      addresses:
        - 10.10.30.2/24
      nameservers:
          addresses: [8.8.8.8, 8.8.4.4]
      routes:
        - to: 0.0.0.0/0
          via: 10.10.30.1
          metric: 99
    ens19:
      dhcp4: true
      routes:
        - to: 192.168.98.0/24
          via: 192.168.98.1
          metric: 100
  version: 2